#+TITLE: About

Here a few rules of thumb I use for katas:

- A kata is *short*: it should take from a few minutes to at most a
  few hours to complete.

  For example, if I'm studying a long document such as a book, I will
  probably treat every chapter as a new kata, even if the next chapter
  builds on the previous one.

- A kata is *documented*: it should have its own [[file:katas/][kata page]]. It can
  also, and probably should, be part of a [[file:themes/][theme]] sooner or later to
  bring even more structure to the wiki.

  Articles in the documentation should be [[https://web.archive.org/][archived]] to avoid [[https://en.wikipedia.org/wiki/Link_rot][link rot]].

- A kata is *immutable*: it should be left alone after completion. The
  only exceptions are small fixes, such as typos. The documentation
  for a kata can be updated more freely.

- A kata is *useful*: it should, sooner or later, be referenced or
  used somewhere else. Use it as...

  + ...an inspiration for a project, or as an improvement to a
    project. Mention the project in the documentation.

  + ...a source for [[https://apps.ankiweb.net/][Anki cards]] if some key concepts should be
    remembered.

  + ...an answer to somebody's question.

  + Etc.
